"""Initial: all tables

Revision ID: 40f88a383240
Revises: 
Create Date: 2026-04-09 14:09:05.044515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f88a383240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='助手名称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('mbti_type', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbtitype'), nullable=False, comment='MBTI类型'),
    sa.Column('personality', sa.Text(), nullable=True, comment='性格描述'),
    sa.Column('speaking_style', sa.Text(), nullable=True, comment='说话风格'),
    sa.Column('expertise', sa.String(length=500), nullable=True, comment='专长领域'),
    sa.Column('greeting', sa.Text(), nullable=True, comment='开场白'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签,逗号分隔'),
    sa.Column('is_recommended', sa.Boolean(), nullable=True, comment='是否推荐'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assistants_id'), 'ai_assistants', ['id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('content_type', sa.String(length=20), nullable=True, comment='内容类型(text/markdown)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_top', sa.Boolean(), nullable=True, comment='是否置顶'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False, comment='徽章编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='徽章名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='徽章描述'),
    sa.Column('icon', sa.String(length=500), nullable=True, comment='图标URL'),
    sa.Column('rarity', sa.String(length=20), nullable=False, comment='稀有度'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类: 入门/活跃/成就/隐藏'),
    sa.Column('condition_type', sa.String(length=50), nullable=True, comment='解锁条件类型: login_days/conversation_count/diary_count'),
    sa.Column('condition_value', sa.Integer(), nullable=True, comment='条件值'),
    sa.Column('hint', sa.String(length=200), nullable=True, comment='获取提示（对未解锁用户显示）'),
    sa.Column('is_hidden', sa.Boolean(), nullable=True, comment='是否隐藏'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_code'), 'badges', ['badge_code'], unique=True)
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='图片URL'),
    sa.Column('link_url', sa.String(length=500), nullable=True, comment='跳转链接'),
    sa.Column('link_type', sa.String(length=20), nullable=True, comment='跳转类型(internal/external)'),
    sa.Column('position', sa.String(length=20), nullable=True, comment='位置(home/mbti/chat)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容(Markdown)'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='HTML内容'),
    sa.Column('category', sa.Enum('EMOTION', 'RELATIONSHIP', 'SELF_GROWTH', 'PSYCHOLOGY', 'LOVE', 'FAMILY', 'CAREER', name='articlecategory'), nullable=False, comment='分类'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签,逗号分隔'),
    sa.Column('mbti_types', sa.String(length=100), nullable=True, comment='相关MBTI类型,逗号分隔'),
    sa.Column('vector_id', sa.String(length=100), nullable=True, comment='向量ID'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='articlestatus'), nullable=True, comment='状态'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='阅读数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='作者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_table('mbti_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimension', sa.Enum('EI', 'SN', 'TF', 'JP', name='mbtidimension'), nullable=False, comment='所属维度'),
    sa.Column('question_no', sa.Integer(), nullable=False, comment='题目序号(1-48)'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='题目内容'),
    sa.Column('option_a', sa.String(length=500), nullable=False, comment='选项A'),
    sa.Column('option_b', sa.String(length=500), nullable=False, comment='选项B'),
    sa.Column('weight_a', sa.Integer(), nullable=True, comment='选项A权重'),
    sa.Column('weight_b', sa.Integer(), nullable=True, comment='选项B权重'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbti_questions_id'), 'mbti_questions', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('mbti_type', sa.String(length=4), nullable=True, comment='MBTI类型'),
    sa.Column('mbti_result_id', sa.Integer(), nullable=True, comment='MBTI结果ID'),
    sa.Column('member_level', sa.Enum('FREE', 'VIP', 'SVIP', 'ENTERPRISE', name='memberlevel'), nullable=True, comment='会员等级'),
    sa.Column('member_expire_at', sa.DateTime(), nullable=True, comment='会员过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否验证'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否为管理员'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('article_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_collections_id'), 'article_collections', ['id'], unique=False)
    op.create_table('content_audit_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交用户ID'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型: chat/diary/comment'),
    sa.Column('content_id', sa.Integer(), nullable=True, comment='内容ID'),
    sa.Column('content_text', sa.Text(), nullable=False, comment='内容文本'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='风险等级'),
    sa.Column('categories', sa.String(length=200), nullable=True, comment='违规分类，逗号分隔'),
    sa.Column('detected_keywords', sa.String(length=200), nullable=True, comment='检测到的关键词'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='检测置信度'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/processing/approved/rejected'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核管理员ID'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('review_note', sa.String(length=500), nullable=True, comment='审核备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_audit_queue_id'), 'content_audit_queue', ['id'], unique=False)
    op.create_index(op.f('ix_content_audit_queue_user_id'), 'content_audit_queue', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('assistant_id', sa.Integer(), nullable=True, comment='助手ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='对话标题'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数'),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='conversationstatus'), nullable=True, comment='状态'),
    sa.Column('user_mbti', sa.String(length=4), nullable=True, comment='用户MBTI类型'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['assistant_id'], ['ai_assistants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('diary_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标签颜色'),
    sa.Column('use_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_tags_id'), 'diary_tags', ['id'], unique=False)
    op.create_index(op.f('ix_diary_tags_user_id'), 'diary_tags', ['user_id'], unique=False)
    op.create_table('emotion_diaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('mood_score', sa.Integer(), nullable=False, comment='心情评分 1-10'),
    sa.Column('mood_level', sa.Enum('TERRIBLE', 'BAD', 'NEUTRAL', 'GOOD', 'EXCELLENT', name='moodlevel'), nullable=True, comment='心情等级'),
    sa.Column('primary_emotion', sa.Enum('HAPPY', 'EXCITED', 'GRATEFUL', 'PEACEFUL', 'ANXIOUS', 'SAD', 'ANGRY', 'FRUSTRATED', 'LONELY', 'CONFUSED', 'HOPEFUL', 'MOTIVATED', name='emotiontype'), nullable=True, comment='主要情绪'),
    sa.Column('secondary_emotions', sa.JSON(), nullable=True, comment='次要情绪列表'),
    sa.Column('emotion_tags', sa.String(length=500), nullable=True, comment='情绪标签，逗号分隔'),
    sa.Column('content', sa.Text(), nullable=True, comment='日记内容'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='AI生成的摘要'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI情绪分析'),
    sa.Column('ai_suggestion', sa.Text(), nullable=True, comment='AI建议'),
    sa.Column('analysis_status', sa.String(length=20), nullable=True, comment='分析状态: pending/processing/completed/failed'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='自定义标签，逗号分隔'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类：工作/感情/生活/学习/其他'),
    sa.Column('is_shared', sa.Boolean(), nullable=True, comment='是否分享'),
    sa.Column('share_public', sa.Boolean(), nullable=True, comment='是否公开分享'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_diaries_date'), 'emotion_diaries', ['date'], unique=False)
    op.create_index(op.f('ix_emotion_diaries_id'), 'emotion_diaries', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_diaries_user_id'), 'emotion_diaries', ['user_id'], unique=False)
    op.create_table('exp_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='获取动作: chat/diary/login/achievement'),
    sa.Column('exp_gained', sa.Integer(), nullable=False, comment='获得经验'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='关联ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='获取时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exp_records_id'), 'exp_records', ['id'], unique=False)
    op.create_index(op.f('ix_exp_records_user_id'), 'exp_records', ['user_id'], unique=False)
    op.create_table('growth_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型'),
    sa.Column('task_code', sa.String(length=50), nullable=False, comment='任务编码'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='任务标题'),
    sa.Column('description', sa.String(length=300), nullable=True, comment='任务描述'),
    sa.Column('target', sa.Integer(), nullable=False, comment='目标值'),
    sa.Column('current', sa.Integer(), nullable=True, comment='当前进度'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否完成'),
    sa.Column('is_rewarded', sa.Boolean(), nullable=True, comment='是否已领取奖励'),
    sa.Column('reward_exp', sa.Integer(), nullable=True, comment='奖励经验'),
    sa.Column('reward_badge_id', sa.Integer(), nullable=True, comment='奖励徽章ID'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_tasks_id'), 'growth_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_growth_tasks_user_id'), 'growth_tasks', ['user_id'], unique=False)
    op.create_table('mbti_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('answer', sa.String(length=1), nullable=False, comment='答案(A/B)'),
    sa.Column('score', sa.Integer(), nullable=False, comment='得分'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['question_id'], ['mbti_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbti_answers_id'), 'mbti_answers', ['id'], unique=False)
    op.create_table('mbti_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('mbti_type', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbtitype'), nullable=False, comment='MBTI类型'),
    sa.Column('ei_score', sa.Integer(), nullable=False, comment='E-I得分(正数偏E)'),
    sa.Column('sn_score', sa.Integer(), nullable=False, comment='S-N得分(正数偏S)'),
    sa.Column('tf_score', sa.Integer(), nullable=False, comment='T-F得分(正数偏T)'),
    sa.Column('jp_score', sa.Integer(), nullable=False, comment='J-P得分(正数偏J)'),
    sa.Column('report_json', sa.Text(), nullable=True, comment='详细报告JSON'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbti_results_id'), 'mbti_results', ['id'], unique=False)
    op.create_table('member_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='会员等级'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='金额(分)'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='时长(天)'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='支付方式(wechat/alipay/stripe)'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='支付平台交易号'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态(pending/paid/cancelled/refunded)'),
    sa.Column('refund_amount', sa.Integer(), nullable=True, comment='退款金额(分)'),
    sa.Column('refund_at', sa.DateTime(), nullable=True, comment='退款时间'),
    sa.Column('refund_reason', sa.String(length=500), nullable=True, comment='退款原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_member_orders_id'), 'member_orders', ['id'], unique=False)
    op.create_table('mood_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('mood_score', sa.Integer(), nullable=False, comment='心情评分 1-10'),
    sa.Column('mood_level', sa.Enum('TERRIBLE', 'BAD', 'NEUTRAL', 'GOOD', 'EXCELLENT', name='moodlevel'), nullable=True, comment='心情等级'),
    sa.Column('emotion', sa.Enum('HAPPY', 'EXCITED', 'GRATEFUL', 'PEACEFUL', 'ANXIOUS', 'SAD', 'ANGRY', 'FRUSTRATED', 'LONELY', 'CONFUSED', 'HOPEFUL', 'MOTIVATED', name='emotiontype'), nullable=True, comment='情绪'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='简短备注'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='位置（可选）'),
    sa.Column('activity', sa.String(length=100), nullable=True, comment='正在做的事'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_records_id'), 'mood_records', ['id'], unique=False)
    op.create_index(op.f('ix_mood_records_user_id'), 'mood_records', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('badge_id', sa.Integer(), nullable=False, comment='徽章ID'),
    sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='获取时间'),
    sa.Column('is_displayed', sa.Boolean(), nullable=True, comment='是否在个人资料展示'),
    sa.Column('display_note', sa.String(length=200), nullable=True, comment='自定义展示语'),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('current_level', sa.Integer(), nullable=True, comment='当前等级'),
    sa.Column('current_exp', sa.Integer(), nullable=True, comment='当前经验'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.create_table('user_long_term_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('memory_type', sa.String(length=50), nullable=False, comment='记忆类型'),
    sa.Column('importance', sa.Integer(), nullable=True, comment='重要程度 1-4'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='记忆摘要'),
    sa.Column('keywords', sa.String(length=500), nullable=True, comment='关键词，逗号分隔'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源: conversation/diary/user_input'),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True, comment='来源对话ID'),
    sa.Column('source_message_id', sa.Integer(), nullable=True, comment='来源消息ID'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否有效'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否经用户确认'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True, comment='最后访问时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_long_term_memory_id'), 'user_long_term_memory', ['id'], unique=False)
    op.create_index(op.f('ix_user_long_term_memory_memory_type'), 'user_long_term_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_user_long_term_memory_user_id'), 'user_long_term_memory', ['user_id'], unique=False)
    op.create_table('user_memory_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('insight_type', sa.String(length=50), nullable=False, comment='洞察类型'),
    sa.Column('insight_content', sa.Text(), nullable=False, comment='洞察内容'),
    sa.Column('supporting_memory_ids', sa.String(length=200), nullable=True, comment='支持的记忆ID列表，逗号分隔'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度'),
    sa.Column('is_accepted', sa.Boolean(), nullable=True, comment='用户是否接受该洞察'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_insights_id'), 'user_memory_insights', ['id'], unique=False)
    op.create_index(op.f('ix_user_memory_insights_user_id'), 'user_memory_insights', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='键'),
    sa.Column('value', sa.Text(), nullable=False, comment='值'),
    sa.Column('value_type', sa.String(length=20), nullable=True, comment='值类型: string/number/boolean/json'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='对话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色(user/assistant/system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.Enum('TEXT', 'VOICE', 'IMAGE', name='messagetype'), nullable=True, comment='消息类型'),
    sa.Column('extra', sa.Text(), nullable=True, comment='扩展信息JSON'),
    sa.Column('emotion', sa.String(length=50), nullable=True, comment='检测到的情绪'),
    sa.Column('sentiment_score', sa.Integer(), nullable=True, comment='情感得分(-100到100)'),
    sa.Column('is_collected', sa.Boolean(), nullable=True, comment='是否收藏'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('message_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='消息ID'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='收藏备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_collections_id'), 'message_collections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_collections_id'), table_name='message_collections')
    op.drop_table('message_collections')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_memory_insights_user_id'), table_name='user_memory_insights')
    op.drop_index(op.f('ix_user_memory_insights_id'), table_name='user_memory_insights')
    op.drop_table('user_memory_insights')
    op.drop_index(op.f('ix_user_long_term_memory_user_id'), table_name='user_long_term_memory')
    op.drop_index(op.f('ix_user_long_term_memory_memory_type'), table_name='user_long_term_memory')
    op.drop_index(op.f('ix_user_long_term_memory_id'), table_name='user_long_term_memory')
    op.drop_table('user_long_term_memory')
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_mood_records_user_id'), table_name='mood_records')
    op.drop_index(op.f('ix_mood_records_id'), table_name='mood_records')
    op.drop_table('mood_records')
    op.drop_index(op.f('ix_member_orders_id'), table_name='member_orders')
    op.drop_table('member_orders')
    op.drop_index(op.f('ix_mbti_results_id'), table_name='mbti_results')
    op.drop_table('mbti_results')
    op.drop_index(op.f('ix_mbti_answers_id'), table_name='mbti_answers')
    op.drop_table('mbti_answers')
    op.drop_index(op.f('ix_growth_tasks_user_id'), table_name='growth_tasks')
    op.drop_index(op.f('ix_growth_tasks_id'), table_name='growth_tasks')
    op.drop_table('growth_tasks')
    op.drop_index(op.f('ix_exp_records_user_id'), table_name='exp_records')
    op.drop_index(op.f('ix_exp_records_id'), table_name='exp_records')
    op.drop_table('exp_records')
    op.drop_index(op.f('ix_emotion_diaries_user_id'), table_name='emotion_diaries')
    op.drop_index(op.f('ix_emotion_diaries_id'), table_name='emotion_diaries')
    op.drop_index(op.f('ix_emotion_diaries_date'), table_name='emotion_diaries')
    op.drop_table('emotion_diaries')
    op.drop_index(op.f('ix_diary_tags_user_id'), table_name='diary_tags')
    op.drop_index(op.f('ix_diary_tags_id'), table_name='diary_tags')
    op.drop_table('diary_tags')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_content_audit_queue_user_id'), table_name='content_audit_queue')
    op.drop_index(op.f('ix_content_audit_queue_id'), table_name='content_audit_queue')
    op.drop_table('content_audit_queue')
    op.drop_index(op.f('ix_article_collections_id'), table_name='article_collections')
    op.drop_table('article_collections')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_mbti_questions_id'), table_name='mbti_questions')
    op.drop_table('mbti_questions')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.drop_table('banners')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_badge_code'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_ai_assistants_id'), table_name='ai_assistants')
    op.drop_table('ai_assistants')
    # ### end Alembic commands ###
