"""
Schema包
"""
from app.schemas.user import (
    SmsSendRequest,
    SmsVerifyRequest,
    RegisterRequest,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    UserInfo,
    UpdateUserRequest,
    ChangePasswordRequest,
    MemberPrice,
    MemberOrderCreate,
    MemberOrderResponse,
    MemberLevelEnum,
)
from app.schemas.mbti import (
    MbtiQuestionSchema,
    MbtiQuestionListResponse,
    MbtiAnswerSubmit,
    MbtiTestSubmit,
    MbtiDimensionScore,
    MbtiResultSchema,
    MbtiTestStartResponse,
    AiAssistantSchema,
    AiAssistantListResponse,
    RecommendAssistantRequest,
)
from app.schemas.chat import (
    MessageSchema,
    ConversationSchema,
    ChatSendRequest,
    ChatSendResponse,
    ConversationListResponse,
    MessageListResponse,
    ChatHistoryRequest,
    MessageCollectRequest,
    ConversationCreateRequest,
    ConversationTitleUpdate,
)
from app.schemas.knowledge import (
    ArticleSchema,
    ArticleDetailResponse,
    ArticleListResponse,
    ArticleSearchRequest,
    BannerSchema,
    AnnouncementSchema,
    ArticleCollectionRequest,
    ArticleLikeRequest,
)

__all__ = [
    # user
    "SmsSendRequest",
    "SmsVerifyRequest",
    "RegisterRequest",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "UserInfo",
    "UpdateUserRequest",
    "ChangePasswordRequest",
    "MemberPrice",
    "MemberOrderCreate",
    "MemberOrderResponse",
    "MemberLevelEnum",
    # mbti
    "MbtiQuestionSchema",
    "MbtiQuestionListResponse",
    "MbtiAnswerSubmit",
    "MbtiTestSubmit",
    "MbtiDimensionScore",
    "MbtiResultSchema",
    "MbtiTestStartResponse",
    "AiAssistantSchema",
    "AiAssistantListResponse",
    "RecommendAssistantRequest",
    # chat
    "MessageSchema",
    "ConversationSchema",
    "ChatSendRequest",
    "ChatSendResponse",
    "ConversationListResponse",
    "MessageListResponse",
    "ChatHistoryRequest",
    "MessageCollectRequest",
    "ConversationCreateRequest",
    "ConversationTitleUpdate",
    # knowledge
    "ArticleSchema",
    "ArticleDetailResponse",
    "ArticleListResponse",
    "ArticleSearchRequest",
    "BannerSchema",
    "AnnouncementSchema",
    "ArticleCollectionRequest",
    "ArticleLikeRequest",
]